In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [3]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [4]:
x.ndim,x.shape,x.dtype,x.itemsize

(2, (3, 5), dtype('int64'), 8)

In [5]:
y = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [6]:
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [7]:
z = np.array([[9,12,16,50,16],[10,15,20,1,8],[12,15,21,23,24]])
z

array([[ 9, 12, 16, 50, 16],
       [10, 15, 20,  1,  8],
       [12, 15, 21, 23, 24]])

In [8]:
y+z

array([[10, 14, 19, 54, 21],
       [16, 22, 28, 10, 18],
       [23, 27, 34, 37, 39]])

In [9]:
y-z

array([[ -8, -10, -13, -46, -11],
       [ -4,  -8, -12,   8,   2],
       [ -1,  -3,  -8,  -9,  -9]])

In [11]:
y*z #its not matirx multiplication

array([[  9,  24,  48, 200,  80],
       [ 60, 105, 160,   9,  80],
       [132, 180, 273, 322, 360]])

In [15]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
a = np.array([[25,5,1],[4,5,7],[5,3,2],[5,8,4],[1,1,1]])
a

array([[25,  5,  1],
       [ 4,  5,  7],
       [ 5,  3,  2],
       [ 5,  8,  4],
       [ 1,  1,  1]])

In [19]:
x.dot(a) #this is matrix multiplication

array([[ 73,  61,  42],
       [273, 171, 117],
       [473, 281, 192]])

In [21]:
a

array([[25,  5,  1],
       [ 4,  5,  7],
       [ 5,  3,  2],
       [ 5,  8,  4],
       [ 1,  1,  1]])

In [20]:
a.transpose()

array([[25,  4,  5,  5,  1],
       [ 5,  5,  3,  8,  1],
       [ 1,  7,  2,  4,  1]])